<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API_ADO_EmpDept_CRUD.Models\API_ADO_EmpDept_CRUD.Models.csproj" />
    <ProjectReference Include="..\API_ADO_EmpDept_CRUD.Repository\API_ADO_EmpDept_CRUD.Repository.csproj" />
    <ProjectReference Include="..\API_ADO_EmpDept_CRUD.Service\API_ADO_EmpDept_CRUD.Service.csproj" />
  </ItemGroup>

</Project>
